### ISSUE TITLE
First feedback

### ISSUE THREAD

**Issue by phiendp** [khoa0319/holistics-autocomplete#1]
Hi Khoa,

I'm Phien from Holistics. First, thank you for taking the take-home assignment. We really appreciate that you spent your free time to do this assignment, as we understand that this is a time-consuming task. 

One of the assignment's goals is to give you a chance to experience how we perform our daily works at Holistics. Thus, I will review your code and give you some feedback, then you can improve your work later. Please check my feedback below:

1) I've tried calling your search API but seems like the service is unavailable now (got 503 error code). Can you re-check your server again?

2) In your writeup, can you be more specific about how your database process the query string that was sent from the client side? Also including an overview of your system flow from frontend to the backend in this writeup would be nice. The writeup can be saved in a markdown file inside the repository so that we can review it easier.

That's all for now. I would like to say that you are doing great, keep up the good works 👍.

**Comment by khoa0319** [comment]
Thank you for the feedback.
It seems like i the database has some misconfiguration so was down for a period but now it's back online.
For now you can just query with the words from A to I only, i'm so sorry for the inconvenience.
About the specific writeup, i'm writing it at the moment so it's coming soon.

**Comment by phiendp** [comment]
Thank you, Khoa. In your writeup, can you also explain why the user can query the words from A to I only? You don't need to fix that problem or any related bugs, just tell us the reason for that limitation.

**Comment by khoa0319** [comment]
I've uploaded the writeup and some data about the assignment.
Thank you for taking time to feedback.

**Comment by phiendp** [comment]
Thank you, @khoa0319. This issue can be closed now.
